### ISSUE TITLE
Mira

### ISSUE THREAD

**Issue by kaynan013** [kaynan013/RainingDays0.1#7]
O personagem não mira.
Ou melhor, a câmera de mira se movimenta, mas o personagem não executa nenhuma animação para a mira e a câmera não trava a rotação do personagem. Precisa travar.
Em "ThirdPersonCharacter" já está separada a movimentação da câmera, isso pode ser movido pra alguma outra BP que trate somente da movimentação da câmera.
Note que "mirar" IMPLICA em sacar uma arma. O personagem deve sacar a última arma utilizada. Ou seja, deve executar alguma das animações (sacar a besta ou sacar a escopeta).
Não há animação para sacá-las. Precisa ser feita. Isso está em uma Issue separada.

**Comment by LFPaiser** [comment]
Movimentação básica do personagem está toda completa. Vamos fazer uma atualização geral do repositório com um update de Maio/21.
