### ISSUE TITLE
Animações faltantes

### ISSUE THREAD

**Issue by kaynan013** [kaynan013/RainingDays0.1#8]
O personagem deve ter uma animação para cada uma das ações abaixo:

1. IDLE: 
   - arma de mão;

2. ANDANDO: 
   - arma de mão;

3. CORRENDO: 
   - arma de mão;

4. SPRINT: 
   - arma de mão;

5. GUARDANDO:
   - arma de mão;
   - escopeta;

6. SACANDO:
   - arma de mão;
   - escopeta;

7. AGACHADO:
   - arma de mão;

8. ANDANDO AGACHADO:
   - arma de mão;

**Comment by LFPaiser** [comment]
Essa issue foi resolvida e virá no update de Maio/21? Fechá-la-ei se assim for o caso. @kaynan013

**Comment by kaynan013** [comment]
ta feito, bicho
